use_frameworks!

platform :ios, '10.0'

target 'TFLRouter_Example' do
  pod 'TFLRouter', :path => '../'

  target 'TFLRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
